export const PERMISSIONS = {
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_READ: "PRODUCT_READ",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_READ: "CATEGORY_READ",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_READ: "CUSTOMER_READ",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_READ: "SUPPLIER_READ",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  INVENTORY_READ: "INVENTORY_READ",
  INVENTORY_STOCK_IN: "INVENTORY_STOCK_IN",
  INVENTORY_STOCK_OUT: "INVENTORY_STOCK_OUT",
  INVENTORY_ADJUSTMENT: "INVENTORY_ADJUSTMENT",

  ORDER_CREATE: "ORDER_CREATE",
  ORDER_READ: "ORDER_READ",
  ORDER_UPDATE: "ORDER_UPDATE",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];