import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<
  "SUPER_ADMIN" | "USER",
  Permission[]
> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  USER: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CATEGORY_READ,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SUPPLIER_READ,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_STOCK_IN,
    PERMISSIONS.INVENTORY_STOCK_OUT,

    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
  ],
};