import Link from "next/link";
import StoreFooter from "@/components/store/StoreFooter";
import StoreNavbar from "@/components/store/StoreNavbar";

const stories = [["The quiet art of making a room", "Home", "A few small shifts that make a space feel more like your own.", "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=85"], ["What we keep on the bedside table", "Rituals", "Objects for the first light, the last page and everything between.", "https://images.unsplash.com/photo-1600494603989-9650cf6ddd3d?auto=format&fit=crop&w=1200&q=85"], ["Meet the makers: honest materials", "People", "Inside the hands and workshops behind the pieces we choose.", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85"]];

export default function JournalPage() {
  return <main className="min-h-screen bg-[#f0ece5] text-[#25231f]"><StoreNavbar /><section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#b45d43]">The Morrow note</p><h1 className="mt-4 max-w-3xl font-serif text-6xl leading-[0.9] tracking-[-0.06em] sm:text-8xl">Good things,<br />occasionally.</h1><p className="mt-7 max-w-md text-base leading-7 text-[#625e56]">Notes on living with more intention, from the studio and beyond.</p></section><section className="mx-auto max-w-[1440px] px-5 pb-16 sm:px-8 lg:px-12"><div className="grid gap-8 lg:grid-cols-3">{stories.map(([title, category, copy, image]) => <article key={title}><div className="aspect-[1.1] overflow-hidden bg-[#d4c8b8]"><img src={image} alt={title} className="h-full w-full object-cover transition duration-700 hover:scale-105" /></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#b45d43]">{category}</p><h2 className="mt-2 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-[#625e56]">{copy}</p><Link href="/journal" className="mt-5 inline-block border-b border-[#25231f] pb-1 text-[10px] font-semibold uppercase tracking-[0.18em]">Read note</Link></article>)}</div></section><section className="border-y border-[#25231f]/10 bg-[#e7e1d7] px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1100px] gap-8 sm:grid-cols-2"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#b45d43]">From the studio</p><h2 className="mt-4 font-serif text-4xl">Small observations, useful ideas.</h2></div><p className="text-sm leading-7 text-[#625e56]">We write about rooms, rituals, materials and the people who make everyday objects worth keeping.</p></div></section><section className="mx-auto grid max-w-[1100px] gap-8 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-24"><img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85" alt="Notebook and coffee beside a window" className="aspect-[1.1] h-full w-full object-cover" /><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#b45d43]">Slow pages</p><h2 className="mt-4 font-serif text-5xl">A little space to notice more.</h2><p className="mt-5 text-sm leading-6 text-[#625e56]">Useful ideas, beautiful details and stories behind the things we keep.</p></div></section><section className="bg-[#b45d43] px-5 py-16 text-center text-[#f7f4ee] sm:px-8"><h2 className="font-serif text-4xl sm:text-5xl">A good note, now and then.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-white/80">Join our occasional letter for new stories and considered things.</p><Link href="/auth/register" className="mt-7 inline-block border-b border-white pb-2 text-xs font-semibold uppercase tracking-[0.18em]">Join the note</Link></section><StoreFooter /></main>;
}
